name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Delete package_lock.json
        run: rm -f package-lock.json

      - name: Clean cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run workflow-build

      - name: Generate
        run: npm run workflow-generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist